### PR TITLE
SEAPATH_HOST: add intel-cmt-cat and msr-tools to packages list

### PR DESCRIPTION
**Pull request by dknueppe**
Added packages for realtime optimizations that I'd like to have included in the official image in SEAPATH_HOST.

Furthermore added packages in SEAPATH_DBG for more convenience.

### CODE REVIEW

**Comment by insatomcat** [comment]
Thanks for this contribution.
Can you provide an example of how those 2 packages can/will be used in production? What do you have in mind?
Thanks.

**Comment by dknueppe** [comment]
Yeah sure, so here is a script we use to set cache way alloctions.
usually pqos would be used to achieve this (intel-cmt-cat package provides this software) however in our case it didn't support all the cpu's features, so we directly write the msr to set up cache way allocations.

```
#!/bin/bash

# setup Cache-Way masks for COS 0-4
wrmsr 0xc90 0xe00 # 1110 0000 0000
wrmsr 0xc91 0x1fc # 0001 1100 0000
wrmsr 0xc92 0x038 # 0000 0011 1000
wrmsr 0xc93 0x007 # 0000 0000 0111

# cores 0-2 remain in default COS 0
# is equivalent to the following
#pqos -a 'core:1=3-5'
#pqos -a 'core:2=6'
#pqos -a 'core:3=7'
#
# set core 3-5 to use COS 1
wrmsr -p 3 0xc8f 0x100000000
wrmsr -p 4 0xc8f 0x100000000
wrmsr -p 5 0xc8f 0x100000000
# set core 6 to use COS 2
wrmsr -p 6 0xc8f 0x200000000
# set core 7 to use COS 3
wrmsr -p 7 0xc8f 0x300000000
```

https://github.com/dknueppe/seapath-ansible/blob/debian-main/src/cache_allocator.sh

**Comment by dknueppe** [comment]
I used perf to monitor llc load and store cache misses, then ran stress-ng --cache on the non isolated cores (in COS0). This yielded no apperant extra cache misses on the isolated cache ways.

This improved scheduling latencies of a vPAC solution by ~30%.

This could also possibly be interesting from a security perspective.

**Comment by dknueppe** [comment]
I've split the commits, is anything else required?

**Review by ycongal-smile — APPROVED** [review]
> I've split the commits, is anything else required?

Not from my point of view (but I'm no maintainer)

**Comment by insatomcat** [comment]
yes, you have to add the DCO to both your commits please (git commit -s)

**Review by insatomcat — APPROVED** [review]

**Pull request merged**
